title: Blog_Sonali Singh
description: Data enthusiast | Never ending adventure | Always curious
author: Sonali Singh
email: ssingh79@binghamton.edu
phone: 607-352-0778
github: https://github.com/singh-sona
about: I am a Data Analyst inetrn at <a href="https://puppseating.com/" target="_blank">PUPPSeating.com</a>. Always excited to dive deep into ocean of data
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/tmjam3011"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sonali-singh94/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/singh-sona/"

share:
  #twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    #- text: XML Feed
     # url: /feed.xml
# url: "http://localhost:4000"
url: "https://singh-sona.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
